# Generated by Django 2.2 on 2019-10-02 12:12

import blog.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to=blog.models.upload_image_path)),
                ('img_1', models.ImageField(blank=True, upload_to=blog.models.upload_image_path)),
                ('img_2', models.ImageField(blank=True, upload_to=blog.models.upload_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(default='images/comment/3.png', upload_to=blog.models.upload_image_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost')),
            ],
        ),
    ]
