# Generated by Django 2.2 on 2019-10-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191005_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='images/comment/3.png', null=True, upload_to=''),
        ),
    ]
